N_MOVE = 5
N_A = 21
N_B = 21
RENT_PRICE = 10
MOVE_COST = 2
GAMMA = 0.9

RENT_EXPECT_A = 3
RENT_EXPECT_B = 4
RETURN_EXPECT_A = 3
RETURN_EXPECT_B = 2

DEFAULT_P_PATH = 'dynamics_mat/P_all_20_5.npy'
DEFAULT_R_PATH = 'dynamics_mat/R_all_20_5.npy'

### testing
# N_MOVE = 3
# N_A = 11
# N_B = 11
# RENT_PRICE = 10
# MOVE_COST = 2
# GAMMA = 0.9
# RENT_EXPECT_A = 2
# RENT_EXPECT_B = 2
# RETURN_EXPECT_A = 2
# RETURN_EXPECT_B = 2

POLICY_EVAL_TOL = 1E-8